permalink: pretty

theme: jekyll_patternbot

patternbot:

  layouts:
    default: |
      The default layout should be used for almost every page, it includes the website's primary header and footer.
    product: |
      The product layout should be used for displaying the details and design process of the selected project.
  title: "Gabriella Cincoleon"
  description: |
    Gabriella Cincoleon's online graphic design portfolio.
  font_url: "https://fonts.googleapis.com/css?family=Muli:400,700&display=swap"
  rationales:
    typefaces.primary: |
      Muli is the overall typeface because it is a simple, readable and unique. It really defines my style and personality. This will be the only font that is used throughout the entire website.
    colors.primary: |
      Coral is be the main colour of this brand because it is calm and serene yet strong and adventurous.


collections:
  work:
    output: true
