permalink: pretty

theme: jekyll_patternbot

patternbot:
  title: "Gabriella Cincoleon"
  description: |
    Gabriella Cincoleon's online graphic design portfolio.
  font_url: "https://fonts.googleapis.com/css?family=Muli:400,700&display=swap"
  rationales:
    typefaces.primary: |
      Muli is the overall typeface because it is a simple, readable and unique; Just like the rest of the website design.
